export const DISCOUNT_RATES = Object.freeze({
  FIVE_PERCENT: 0.05,
  TEN_PERCENT: 0.1,
  FIFTEEN_PERCENT: 0.15,
  TWENTY_PERCENT: 0.2,
  TWENTY_FIVE_PERCENT: 0.25,
  SURPRISE_SALE: 0.8,
  RECOMMENDED_SALE: 0.95,
});
