const DISCOUNT_RATES = {
  TEN_PERCENT: 0.1,
  FIFTEEN_PERCENT: 0.15,
  TWENTY_PERCENT: 0.2,
  FIVE_PERCENT: 0.05,
  TWENTY_FIVE_PERCENT: 0.25,
};

const FLASH_SALE_DISCOUNT_RATE = 0.8;

const RECOMMEND_DISCOUNT_RATE = 0.95;

export { DISCOUNT_RATES, FLASH_SALE_DISCOUNT_RATE, RECOMMEND_DISCOUNT_RATE };
